### ISSUE TITLE
Problem: Mainnet is not using Keplr default chain

### ISSUE THREAD

**Issue by calvinaco** [crypto-org-chain/nft-webtool#3]
Right now when choosing Mainnet, it will attempt to create a new network. But mainet is already supported on Keplr in the default chain list. So we should be able to use it directly?

**Comment by cdc-Hitesh** [comment]
It should be able to check it for the injected version. 
i am on it.

**Comment by cdc-Hitesh** [comment]
@calvinaco 
I did a quick check with the current code.

Actually, I am only adding config from `StaticConfig` just for `Testnet 3`
for mainnet it's relying on just the chain-id value in string.

Also, as per the documentation, if an already supported network is added to our code, it acts idempotently.
