### ISSUE TITLE
Problem: Testnet Croeseid-3 is using production walletUrl?

### ISSUE THREAD

**Issue by calvinaco** [crypto-org-chain/nft-webtool#4]
This is a question to the StaticConfig file. In Croeseid-3 Testnet, I notice it is using the Keplr walletUrl, which seems to work only for mainnet. I am not sure what will be the implication when not providing this config. But I notice now there is a stake button:
![image](https://user-images.githubusercontent.com/38898718/129548972-cffab854-9401-4a0d-a7e9-54f0a4c5c5f5.png)

Should we ignore this field instead?

```
  walletUrl:
    process.env.NODE_ENV === "production"
      ? "https://wallet.keplr.app/#/crypto-org/stake"
      : "http://localhost:8081/#/crypto-org/stake",
  walletUrlForStaking:
    process.env.NODE_ENV === "production"
      ? "https://wallet.keplr.app/#/crypto-org/stake"
      : "http://localhost:8081/#/crypto-org/stake",
```

https://github.com/crypto-org-chain/nft-webtool/blob/dev/src/config/StaticConfig.ts#L246

**Comment by cdc-Hitesh** [comment]
Let me try it with no settings provided.
Not sure of the implications

**Comment by cdc-Hitesh** [comment]
I checked with the documentation, these links are optional hence can be discarded for Testnet-3 configuration.
